version: "3.9"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "am"
    volumes:
      - ./app:/app/
      - ./test:/app/test/
    ports:
      - "8001:8001"
    restart: always
    command: python ./main.py
    #command: gunicorn -b :8000 --access-logfile - --error-logfile - main:app
    #command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - am

networks:
  am:
    name: am-net